# netlify.toml
# Redirect rules to support Auth0 callback and SPA routing.

[[redirects]]
  # Auth0 callback redirect
  from = "/auth/callback"
  to = "/login.html"
  status = 200
  force = true

[[redirects]]
  # Logout redirect -> Auth0 logout endpoint
  from = "/logout"
  to = "https://dev-g5g1aikxy6y2dolh.au.auth0.com/v2/logout?returnTo=https://thaimonel.netlify.app/login.html&client_id=nIE7zj5314lyD3wTfRIBtJ5ejZxePSoK"
  status = 302
  force = true

[[redirects]]
  # Catch-all: serve login.html for SPA routes
  from = "/*"
  to = "/login.html"
  status = 200
